/* INDICAÇÃO PARA USAR A TABELA X*/
use vendas_sucos;

/* CRIAÇÃO DA PRIMEIRA TABELA*/
CREATE TABLE PRODUTOS
(CODIGO VARCHAR(10) NOT NULL,
DESCRITOR VARCHAR(100) NULL,
SABOR VARCHAR(50) NULL,
TAMANHO VARCHAR(50) NULL,
EMBALAGEM VARCHAR(50) NULL,
PRECO_LISTA FLOAT NULL,
PRIMARY KEY (CODIGO));

/*CRIAÇÃO DA SEGUNDA TABELA*/
CREATE TABLE VENDEDORES
(MATRICULA VARCHAR(5) NOT NULL,
NOME VARCHAR(100) NULL,
BAIRRO VARCHAR(50) NULL,
COMISSAO FLOAT NULL,
DATA_ADIMISSAO DATE NULL,
FERIAS BIT(1) NULL,
PRIMARY KEY (MATRICULA));

/* ALTERAR ALGUMA COISA DA TABELA*/
ALTER TABLE VENDEDORES RENAME column DATA_ADIMISSAO TO DATA_ADMISSAO;