CREATE TABLE TAB_FATURAMENTO
(DATA_VENDA DATE NULL, TOTAL_VENDA FLOAT);

SELECT * FROM TAB_FATURAMENTO;

/* DELETANDO TODAS AS INFORMAÇOES DAS DUAS TABELAS */
DELETE FROM ITENS_NOTAS;
DELETE FROM NOTAS;

SELECT * FROM NOTAS;
SELECT * FROM ITENS_NOTAS;

SELECT * FROM CLIENTES;
SELECT * FROM VENDEDORES;
SELECT * FROM PRODUTOS;

DELETE FROM TAB_FATURAMENTO;
SELECT * FROM TAB_FATURAMENTO;

INSERT INTO NOTAS (NUMERO, DATA_VENDA, CPF, MATRICULA, IMPOSTO)
VALUES ('0100', '2019-05-08', '1471156710', '235', 0.10);
INSERT INTO ITENS_NOTAS ( NUMERO, CODIGO, QUANTIDADE, PRECO)
VALUES ('0100', '1000889', 100, 10);
INSERT INTO ITENS_NOTAS ( NUMERO, CODIGO, QUANTIDADE, PRECO)
VALUES ('0100', '1002334', 100, 10);

INSERT INTO NOTAS (NUMERO, DATA_VENDA, CPF, MATRICULA, IMPOSTO)
VALUES ('0101', '2019-05-08', '1471156710', '235', 0.10);
INSERT INTO ITENS_NOTAS ( NUMERO, CODIGO, QUANTIDADE, PRECO)
VALUES ('0101', '1000889', 100, 10);
INSERT INTO ITENS_NOTAS ( NUMERO, CODIGO, QUANTIDADE, PRECO)
VALUES ('0101', '1002334', 100, 10);


INSERT INTO NOTAS (NUMERO, DATA_VENDA, CPF, MATRICULA, IMPOSTO)
VALUES ('0103', '2019-05-08', '1471156710', '235', 0.10);
INSERT INTO ITENS_NOTAS ( NUMERO, CODIGO, QUANTIDADE, PRECO)
VALUES ('0103', '1000889', 100, 10);
INSERT INTO ITENS_NOTAS ( NUMERO, CODIGO, QUANTIDADE, PRECO)
VALUES ('0103', '1002334', 100, 10);

INSERT INTO TAB_FATURAMENTO
/* Select para saber o faturamento e a data do faturamento */
SELECT A.DATA_VENDA, SUM(B.QUANTIDADE * B.PRECO) AS TOTAL_VENDA FROM 
NOTAS A INNER JOIN ITENS_NOTAS B
ON A.NUMERO = B.NUMERO
GROUP BY A.DATA_VENDA;

SELECT * FROM TAB_FATURAMENTO;

INSERT INTO NOTAS (NUMERO, DATA_VENDA, CPF, MATRICULA, IMPOSTO)
VALUES ('0104', '2019-05-08', '1471156710', '235', 0.10);
INSERT INTO ITENS_NOTAS ( NUMERO, CODIGO, QUANTIDADE, PRECO)
VALUES ('0104', '1000889', 100, 10);
INSERT INTO ITENS_NOTAS ( NUMERO, CODIGO, QUANTIDADE, PRECO)
VALUES ('0104', '1002334', 100, 10);

INSERT INTO NOTAS (NUMERO, DATA_VENDA, CPF, MATRICULA, IMPOSTO)
VALUES ('0105', '2019-05-08', '1471156710', '235', 0.10);
INSERT INTO ITENS_NOTAS ( NUMERO, CODIGO, QUANTIDADE, PRECO)
VALUES ('0105', '1000889', 100, 10);
INSERT INTO ITENS_NOTAS ( NUMERO, CODIGO, QUANTIDADE, PRECO)
VALUES ('0105', '1002334', 100, 10);
DELETE FROM TAB_FATURAMENTO; /* Não replica os valores e não repete as datas, mostra somente o valor total */
INSERT INTO TAB_FATURAMENTO
SELECT A.DATA_VENDA, SUM(B.QUANTIDADE * B.PRECO) AS TOTAL_VENDA FROM 
NOTAS A INNER JOIN ITENS_NOTAS B
ON A.NUMERO = B.NUMERO
GROUP BY A.DATA_VENDA;


DELIMITER // /* DELIMITADOR É O // (IGNORA OS ; E SÓ FINALIZA QUANDO ENCONTRA O // QUE PODERIA SER OUTRO SINAL "$" */
CREATE TRIGGER TG_CALCULA_FATURAMENTO_INSERT AFTER INSERT ON ITENS_NOTAS
FOR EACH ROW BEGIN /* Aqui terá comandos delimitados CALCULAR O FATURAMENTO TOTAL E GRAVAR NA TABELA*/
	DELETE FROM TAB_FATURAMENTO;
	INSERT INTO TAB_FATURAMENTO
	SELECT A.DATA_VENDA, SUM(B.QUANTIDADE * B.PRECO) AS TOTAL_VENDA FROM 
	NOTAS A INNER JOIN ITENS_NOTAS B
	ON A.NUMERO = B.NUMERO
	GROUP BY A.DATA_VENDA;
END// /* DELIMITADOR É O // */









